version: '3.8'

services:
  app:
    image: selenium/standalone-chrome:latest
    container_name: raspagem_container
    platform: linux/arm64
    volumes:
      - .:/app
    working_dir: /app
    command: python3 main.py
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
