version: '3.8'

services:
  myspeed:
    build: .
    container_name: select_myspeed_container
    restart: always # Isso reinicia o container automaticamente se ele falhar
    volumes:
      - /DATA/AppData/myspeed/data/storage.db:/app/data/storage.db
    environment:
      - TZ=America/Sao_Paulo
